# Simple yaml config-driven schema which is used to define model attributes,
# index key names, and form properties.
#
# Attributes must have a type but all other configuration options are optional.
# Please note: If using Valkyrie's Fedora Metadata Adapter, predicates for attributes
# must be placed here.
#
# attributes:
#   attribute_name:
#     type: string
#     multiple: false
#     index_keys:
#       - "attribute_name_sim"
#     form:
#       required: true
#       primary: true
#       multiple: false
#
# @see config/metadata/basic_metadata.yaml for an example configuration
#
# Generated via
#  `rails generate hyrax:collection_resource CollectionResource`

# This is a copy of the basic_metadata.yaml because we override basic_metadata.yaml and making it.
# We do this because we are grouping everything into the *_resource.yaml for more customizations.
attributes:
  abstract:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "abstract_sim"
      - "abstract_tesim"
    predicate: http://purl.org/dc/terms/abstract
  access_right:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "access_right_sim"
      - "access_right_tesim"
    predicate: http://purl.org/dc/terms/accessRights
  alternative_title:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "alternative_title_sim"
      - "alternative_title_tesim"
    predicate: http://purl.org/dc/terms/alternative
  arkivo_checksum:
    type: string
    multiple: false
    form:
      primary: false
    predicate: http://scholarsphere.psu.edu/ns#arkivoChecksum
  bibliographic_citation:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "bibliographic_citation_sim"
      - "bibliographic_citation_tesim"
    predicate: http://purl.org/dc/terms/bibliographicCitation
  collection_subtitle:
    type: string
    multiple: true
    form:
      primary: true
    index_keys:
      - 'collection_subtitle_sim'
      - 'collection_subtitle_tesim'
  contributor:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "contributor_tesim"
      - "contributor_sim"
    predicate: http://purl.org/dc/elements/1.1/contributor
  creator:
    type: string
    multiple: true
    form:
      required: false
      primary: false
    index_keys:
      - "creator_sim"
      - "creator_tesim"
    predicate: http://purl.org/dc/elements/1.1/creator
  date_created:
    type: date_time
    multiple: true
    form:
      primary: false
    index_keys:
      - "date_created_sim"
      - "date_created_tesim"
    predicate: http://purl.org/dc/terms/created
  description:
    type: string
    multiple: true
    form:
      primary: true
    index_keys:
      - "description_sim"
      - "description_tesim"
    predicate: http://purl.org/dc/elements/1.1/description
  identifier:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "identifier_sim"
      - "identifier_tesim"
    predicate: http://purl.org/dc/terms/identifier
  import_url:
    type: string
    predicate: http://scholarsphere.psu.edu/ns#importUrl
  keyword:
    type: string
    multiple: true
    index_keys:
      - "keyword_sim"
      - "keyword_tesim"
    form:
      primary: false
    predicate: http://schema.org/keywords
  publisher:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "publisher_sim"
      - "publisher_tesim"
    predicate: http://purl.org/dc/elements/1.1/publisher
  label:
    type: string
    form:
      primary: false
    index_keys:
      - "label_sim"
      - "label_tesim"
    predicate: info:fedora/fedora-system:def/model#downloadFilename
  language:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "language_sim"
      - "language_tesim"
    predicate: http://purl.org/dc/elements/1.1/language
  license:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "license_sim"
      - "license_tesim"
    predicate: http://purl.org/dc/terms/license
  relative_path:
    type: string
    predicate: http://scholarsphere.psu.edu/ns#relativePath
  related_url:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "related_url_sim"
      - "related_url_tesim"
    predicate: http://www.w3.org/2000/01/rdf-schema#seeAlso
  resource_type:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "resource_type_sim"
      - "resource_type_tesim"
    predicate: http://purl.org/dc/terms/type
  rights_notes:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "rights_notes_sim"
      - "rights_notes_tesim"
    predicate: http://purl.org/dc/elements/1.1/rights
  rights_statement:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "rights_statement_sim"
      - "rights_statement_tesim"
    predicate: http://www.europeana.eu/schemas/edm/rights
  source:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "source_sim"
      - "source_tesim"
    predicate: http://purl.org/dc/terms/source
  subject:
    type: string
    multiple: true
    index_keys:
      - "subject_sim"
      - "subject_tesim"
    form:
      primary: false
    predicate: http://purl.org/dc/elements/1.1/subject
