name: 'Build Test Lint'
run-name: Build Test Lint of ${{ github.ref_name }} by @${{ github.actor }}
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  build:
    uses: scientist-softserv/actions/.github/workflows/build.yaml@v0.0.22
    secrets: inherit
    with:
      platforms: 'linux/amd64'
      webTarget: hyku-web
      workerTarget: hyku-worker

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2' 
    - name: Install tmate
      run: sudo apt-get install -y tmate
    - name: Run tmate session
      run: |
        tmate -S /tmp/tmate.sock new-session -d
        tmate -S /tmp/tmate.sock wait tmate-ready
        echo "SSH to the runner: $(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')"
        echo "Web to the runner: $(tmate -S /tmp/tmate.sock display -p '#{tmate_web}')"
    - name: Install dependencies
      run: gem install semaphore_test_boosters && bundle install
    - name: Run tests
      run: rspec_booster --job $CI_NODE_INDEX/$CI_NODE_TOTAL

  lint:
    needs: build
    uses: scientist-softserv/actions/.github/workflows/lint.yaml@v0.0.22
    with:
      webTarget: hyku-web
      workerTarget: hyku-worker
      rubocop_cmd: "cd .. && bundle && bundle exec rubocop --parallel --format progress"
